import { MealSchema, RecipeAgentState } from "../agent/state";
import { model } from "../config/model";
import { DailyMealSearchPrompt, WeeklyMealSearchPrompt } from "../prompts";
import { z } from "zod";

export const mealSuggesterNode = async (state: typeof RecipeAgentState.State) => {
    try {
        console.log("[MealSuggester] Starting meal suggestion...");
        
        if (!state.recipeQuery) {
            throw new Error("Recipe query is missing from state");
        }

        const mealQuery = state.recipeQuery;
        
        const MealsResponseSchema = z.object({
            meals: z.array(MealSchema)
        });
        
        // Get AI to generate meal suggestion
        console.log("[MealSuggester] Invoking AI to generate meal suggestion...");
        const structuredMeals = model.withStructuredOutput(MealsResponseSchema);
        let response;
        if(mealQuery.mode === "daily") {
            response = await structuredMeals.invoke(DailyMealSearchPrompt(JSON.stringify(mealQuery)));
        } else {
            response = await structuredMeals.invoke(WeeklyMealSearchPrompt(JSON.stringify(mealQuery)));
        }

        // Validate response
        const validatedData = MealsResponseSchema.parse(response);
        
        if (!validatedData.meals || validatedData.meals.length === 0) {
            throw new Error("No meals were generated by the AI");
        }

        console.log("[MealSuggester] Successfully generated meals:", validatedData.meals);
        
        return { meals: validatedData.meals };
        
    } catch (error) {
        console.error("[MealSuggester] Error:", error);
        
        if (error instanceof z.ZodError) {
            console.error("[MealSuggester] Validation error:", error.issues);
            throw new Error(`Meal validation failed: ${error.issues.map((e: z.ZodIssue) => e.message).join(", ")}`);
        }
        
        throw error;
    }
};

