/**
 * Meal Suggester Node
 * 
 * First node in the recipe planning workflow.
 * Uses AI to generate meal suggestions based on user preferences.
 * 
 * Responsibilities:
 * - Generate 1 meal (daily mode) or 7 meals (weekly mode)
 * - Include search keywords and fallback keywords for each meal
 * - Handle user feedback for regeneration (weekly mode)
 * - Validate AI output against MealSchema
 * 
 * Input State:
 * - recipeQuery: User's meal planning preferences
 * - userFeedback: Optional feedback from human review (regeneration only)
 * 
 * Output State:
 * - meals: Array of meal suggestions with keywords
 * - userFeedback: Cleared after use
 * - needsRegeneration: Cleared after use
 * 
 * Next Node:
 * - mealPicker: Searches Spoonacular for matching recipes
 */

import { MealSchema, RecipeAgentState } from "../agent/state";
import { model } from "../config/model";
import { DailyMealSearchPrompt, WeeklyMealSearchPrompt } from "../prompts";
import { z } from "zod";

export const mealSuggesterNode = async (state: typeof RecipeAgentState.State) => {
    try {
        if (!state.recipeQuery) {
            throw new Error("Recipe query is missing from state");
        }

        const mealQuery = state.recipeQuery;
        
        // Response schema for AI structured output
        const MealsResponseSchema = z.object({
            meals: z.array(MealSchema)
        });
        
        const structuredMeals = model.withStructuredOutput(MealsResponseSchema);
        let response;
        
        // Daily mode: Generate 1 meal
        if(mealQuery.mode === "daily") {
            const prompt = DailyMealSearchPrompt(JSON.stringify(mealQuery));
            response = await structuredMeals.invoke(prompt);
        } 
        // Weekly mode: Generate 7 meals (one per day)
        else {
            let prompt = WeeklyMealSearchPrompt(JSON.stringify(mealQuery));
            
            // Append user feedback if this is a regeneration
            // This allows AI to address user's concerns while keeping preferences
            if (state.userFeedback) {
                prompt += `\n\nIMPORTANT: The user has provided feedback on the previous meal plan. Please regenerate considering this feedback:\nUser Feedback: ${state.userFeedback}\n\nGenerate a new meal plan that addresses the user's concerns while maintaining the original preferences.`;
            }
            
            response = await structuredMeals.invoke(prompt);
        }

        // Validate AI response against schema
        const validatedData = MealsResponseSchema.parse(response);
        
        if (!validatedData.meals || validatedData.meals.length === 0) {
            throw new Error("No meals were generated by the AI");
        }
        
        // Return updated state with meals
        // Clear feedback and regeneration flags after use
        return { 
            meals: validatedData.meals,
            userFeedback: undefined,
            needsRegeneration: undefined
        };
        
    } catch (error) {
        console.error("[MealSuggester] Error:", error);
        
        // Provide detailed error message for validation failures
        if (error instanceof z.ZodError) {
            console.error("[MealSuggester] Validation error:", error.issues);
            throw new Error(`Meal validation failed: ${error.issues.map((e: z.ZodIssue) => e.message).join(", ")}`);
        }
        
        throw error;
    }
};

