import { MealSchema, RecipeAgentState } from "../agent/state";
import { model } from "../config/model";
import { DailyMealSearchPrompt, WeeklyMealSearchPrompt } from "../prompts";
import { z } from "zod";

export const mealSuggesterNode = async (state: typeof RecipeAgentState.State) => {
    try {
        console.log("[MealSuggester] Starting meal suggestion...");
        
        if (!state.recipeQuery) {
            throw new Error("Recipe query is missing from state");
        }

        const mealQuery = state.recipeQuery;
        
        // Check if this is a regeneration with user feedback
        if (state.userFeedback) {
            console.log("[MealSuggester] Regenerating with user feedback:", state.userFeedback);
        }
        
        const MealsResponseSchema = z.object({
            meals: z.array(MealSchema)
        });
        
        // Get AI to generate meal suggestion
        console.log("[MealSuggester] Invoking AI to generate meal suggestion...");
        const structuredMeals = model.withStructuredOutput(MealsResponseSchema);
        let response;
        
        if(mealQuery.mode === "daily") {
            const prompt = DailyMealSearchPrompt(JSON.stringify(mealQuery));
            response = await structuredMeals.invoke(prompt);
        } else {
            let prompt = WeeklyMealSearchPrompt(JSON.stringify(mealQuery));
            
            // Append user feedback if regenerating
            if (state.userFeedback) {
                prompt += `\n\nIMPORTANT: The user has provided feedback on the previous meal plan. Please regenerate considering this feedback:\nUser Feedback: ${state.userFeedback}\n\nGenerate a new meal plan that addresses the user's concerns while maintaining the original preferences.`;
            }
            
            response = await structuredMeals.invoke(prompt);
        }

        // Validate response
        const validatedData = MealsResponseSchema.parse(response);
        
        if (!validatedData.meals || validatedData.meals.length === 0) {
            throw new Error("No meals were generated by the AI");
        }

        console.log("[MealSuggester] Successfully generated meals:", validatedData.meals);
        
        // Clear feedback after using it
        return { 
            meals: validatedData.meals,
            userFeedback: undefined,
            needsRegeneration: undefined
        };
        
    } catch (error) {
        console.error("[MealSuggester] Error:", error);
        
        if (error instanceof z.ZodError) {
            console.error("[MealSuggester] Validation error:", error.issues);
            throw new Error(`Meal validation failed: ${error.issues.map((e: z.ZodIssue) => e.message).join(", ")}`);
        }
        
        throw error;
    }
};

